global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: [ '172.18.0.3:9308' ]
        labels:
          instance: 'kafka-exporter-1'

  - job_name: 'auth-service'
    static_configs:
      - targets: ['127.0.0.1:9053']
        labels:
          instance: 'auth-service-1'
    metrics_path: '/q/metrics'
    scrape_interval: 2s
