name: Build and Deploy Auth Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: suehunpark/auth-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ github.token }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --no-daemon


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Get Git commit hash
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            REAL_SHA=${{ github.event.pull_request.head.sha }}
          else
            REAL_SHA=${{ github.sha }}
          fi
          echo "GIT_COMMIT=$(echo $REAL_SHA | cut -c1-7)" >> $GITHUB_OUTPUT


      - name: Build and Push Docker Image with Jib
        run: |
          ./gradlew build \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.image=${{ env.DOCKER_IMAGE }} \
            -Dquarkus.container-image.tag=${{ steps.vars.outputs.GIT_COMMIT }} \
            -Dquarkus.container-image.additional-tags=latest \
            -Dquarkus.container-image.username=${{ secrets.DOCKER_USERNAME }} \
            -Dquarkus.container-image.password=${{ secrets.DOCKER_PASSWORD }} \
            -x test --no-daemon

      - name: Image Details
        run: |
          echo "âœ… Docker Image Published:"
          echo "ðŸ“¦ Image: ${{ env.DOCKER_IMAGE }}:${{ steps.vars.outputs.GIT_COMMIT }}"


      - name: Deploy to Nomad
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NOMAD_SERVER_HOST }}
          username: ${{ secrets.NOMAD_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            export NOMAD_ADDR=${{ secrets.NOMAD_INTERNAL_ADDR }}
            
            echo "Target Image Tag: ${{ steps.vars.outputs.GIT_COMMIT }}"

            nomad job run \
              -var="image_tag=${{ steps.vars.outputs.GIT_COMMIT }}" \
              /opt/nomad-jobs/app/auth.nomad

            nomad job status auth
            echo "âœ… Deployment triggered on Nomad server."